version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: rollup
    versions:
    - 2.35.1
    - 2.38.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.19
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
  - dependency-name: rollup-plugin-typescript2
    versions:
    - 0.29.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
